### ISSUE TITLE
Allow use of default SSH credentials in CLI

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/prototype#103]
The CLI currently requires that a specific `--identity` be passed in for use with SSH, and aborts any subcommands requiring SSH if that argument is missing.

To allow the use of default SSH keys and ssh-agent, we want to make that setting optional, and delegate authentication to SSH if no identity file is given.

Actually making this change is straightforward (default the identity file to `None` and skip setting it in that case), but covering it in the integration tests would be a bit more involved.

Based on the work already done for the WIP Cockpit plugin integration test, one way to do that would be to:

- move the user definition helpers out of the plugin testing steps file and into the shared test context
- create a suitably configured test user and add the predefined testing key as their `~/.ssh/id_rsa/` key
- run the affected commands as that user and show that they still work in an end-to-end scenario

However, I'm wondering if it really makes sense to test this as an integration test - we can trust that end-to-end SSH with default credentials works, we just want to ensure that our CLI is configuring *SSH* as expected when no identity file is given.

A potentially more sensible alternative would be to start building out a CLI level unit testing capability - that could then test the CLI arguments -> SSH configuration aspect directly, and avoid running the full integration tests twice with different authentication methods.

**Comment by shaded-enmity** [comment]
From my POV I'd consider relying on default keys a kludge, and treat it as such.

> we just want to ensure that our CLI is configuring SSH as expected when no identity file is given

Technically I think this touches both topics, so for:

1) Unit tests
    We prove that if `--identity FILE` is given the resulting ssh options will contain the key/value `-o IdentityFile FILE`, conversely if no `--identity FILE` is given there should be no additional SSH option
2) Integration tests
    We prove that using the given identity `FILE` we can connect to remote SSH server configured with matching public key AND we can also prove that given a pre-configured key t the process should also succeed without explicit identity file, the test should cover these settings and outcomes:

    | Has `--identity` | Has key in defaults | Connected? |
    |--------------------|--------------------------|-----------------|
    | N | N | N |
    | Y | N | Y |
    | N | Y | Y |
    | Y | Y | Y |

    (Similarity with `C = A | B` function strictly coincidental)

On a related note, we should figure out how much time we want to commit to this since we haven't  really decided our way around https://trello.com/c/4IoVdnrI/47-cli-switch-to-ansible-for-remote-access which might invalidate some of this work

**Comment by ncoghlan** [comment]
Public link for the Ansible discussion: https://github.com/leapp-to/prototype/issues/13

I'm not too worried on that front, as our authentication testing scenarios will conceptually stay the same at both levels, we'll just be generating an Ansible config file instead of an SSH one.

I like your suggested breakdown, so what I'll do for now is to use `destroy-containers` as the example integration testing command, since that's pretty quick to run and only requires a single target VM. Those test scenarios can then go in a `remote-authentication.feature` test file.

Building the unit test infrastructure to show that `destroy-containers`, `migrate-machine` and any other remote access commands we add are all using the same remote connection management backend (and are all using it correctly) can wait for now.
