### ISSUE TITLE
Pre-emptively remove the "ipv4-" prefix from addresses

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/prototype#12]
The tests, the Cockpit plugin, and (as part of #11) leapp-tool itself now have code to strip the `ipv4-` prefix from reported IP addresses.

It will make more sense to strip that prefix pre-emptively, and report IP addresses as plain IP addresses.

**Comment by shaded-enmity** [comment]
Yup, the prefix is a remnant of me fooling around with libvirt response objects. People shouldn't either care about the IP address type and if they do, something like `is_ipv6 = ip.count(':') > 1` should be sufficient.

**Comment by ncoghlan** [comment]
Pull request at https://github.com/leapp-to/prototype/pull/17

Integration tests still pass, currently checking the state of the demo plugin.

**Comment by ncoghlan** [comment]
The demo plugin has problems, but not related to this change, so I filed a separate issue: https://github.com/leapp-to/prototype/issues/20

**Comment by shaded-enmity** [comment]
#17 merged, closing this one and let's track the related issue in #20.
