### ISSUE TITLE
Firewall blocking port scanning

### ISSUE THREAD

**Issue by JacobCZ** [leapp-to/prototype#124]
When ```firewalld``` is running on the host, the ```leapp-tool port-inspect --shallow``` will randomly work and not work.

Workaround for this is to disable firewalld with ```systemctl disable firewalld && systemctl stop firewalld```

**Comment by mfranczy** [comment]
Do we want to disable firewalld? We have issue with netstat (or ss) https://github.com/leapp-to/prototype/issues/68

**Comment by JacobCZ** [comment]
@mfranczy It's the easiest and fastest way to tackle this problem, but perhaps there is a better way to do it...

**Comment by mfranczy** [comment]
I think we can close that issue, the reason why is we don't wanna to stop firewalld
