### ISSUE TITLE
Create a shared "leappto-test-vm" Ansible role

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/prototype#14]
We want some common items set up when creating all leappto test VMs:

- running yum update
- installing some helpful local utilities
- installing the predefined testing key

At the moment, the role for this is duplicated across all the Vagrant VM definitions for the demo plugin and the integrations tests (which means 5 different copies), and that's only going to get worse as more testing and demonstration scenarios are added.

We should tidy this up by creating a location in the repo for shared Ansible roles, adding a `leappto-test-vm` role, and updating all the Vagrant playbooks to use that instead of duplicating those common settings in their own `init` roles.

**Comment by ncoghlan** [comment]
According to http://docs.ansible.com/ansible/playbooks_roles.html#roles we should be able to do this by setting http://docs.ansible.com/ansible/intro_configuration.html#roles-path appropriately, given a common location for shared roles.

The environment variable for doing that is `ANSIBLE_ROLES_PATH`: https://github.com/ansible/ansible/blob/devel/lib/ansible/constants.py#L199

**Comment by shaded-enmity** [comment]
Closed in 6c3befc63570cee94932465375bc52b87c0b5558
