### ISSUE TITLE
demo does not work using the instructions at http://leapp.readthedocs.io/en/latest/getstarted.html

### ISSUE THREAD

**Issue by pcahyna** [leapp-to/prototype#161]
When I try to prepare & run the demo using the instructions at http://leapp.readthedocs.io/en/latest/getstarted.html , there are multiple issues:
- demo/start_vms.sh does not exist (since a1e8cbbf37c986fedcb66b152457394cc88f09de)
- when I fix that (with the help of http://leapp.readthedocs.io/en/latest/adddemo.html), ssh in the demo gives "permission denied", b/c it tries to log in to the VMs as pcahyna, not as vagrant (since 6e19c02f0d9378e0755870101842329a42289002)
- I also need to provision the VMs as the same user who runs the demo (see the log message of 59c9c23b627dfc48034715408b6d09c88bc9e665), and since the demo runs under sudo, one needs to use sudo for provisioning as well.

**Comment by pcahyna** [comment]
PR: #162

**Comment by shaded-enmity** [comment]
Closed via #162
