### ISSUE TITLE
nmap isn't called with elevated privileges as needed

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/prototype#165]
Running the tests as a non-root user currently fails some tests with the following error:

    nmap.nmap.PortScannerError: u'You requested a scan type which requires root privileges.\nQUITTING!\n'

**Comment by ncoghlan** [comment]
After looking into this, the problem is actually on the tests side - `migrate-machine` always needs to be run as root at the moment.

I'll include a fix for this in #167

**Comment by vinzenz** [comment]
@ncoghlan Also port-inspect should be run as root

**Comment by ncoghlan** [comment]
@vinzenz You're right, trying those locally, they're currently failing as a non-root user, and culprit is that the tests are only escalating privileges for `port-detect --shallow`, rather than escalating unconditionally.

**Comment by ncoghlan** [comment]
Rather than continuing the current approach of scattering `as_sudo=True` through the test cases, I'm instead making the CLI helper aware of which commands inherently require root privileges, and having it implicitly set `as_sudo` in those cases.
