### ISSUE TITLE
Problems with running Cockpit demo

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/prototype#20]
I tried running the Cockpit demo for the first time since adding the integration tests, and found a couple of problems:

- the known SSH key is being loaded from the wrong path in the Ansible roles
- the migration script is assuming the migrated HTTP service in on port 80 (to match the integration tests), when the demo still expects it to be on port 9000

The former is easy to fix and I've submitted a PR for that in https://github.com/leapp-to/prototype/pull/19

For the latter, we need to decide *how* we want to fix it for the time being.

My suggestion is that, for now, we just add a `--tcp-port` option to `migrate-machine` that can be used to override the default `-p 80:80` option used by the integration tests (we'd leave the `-p 9022:22` for SSH forwarding to the macrocontainer hardcoded).

The demo plugin would then be updated to add `--tcp-port 9000:80` to configure the macrocontainer host correctly.

**Comment by shaded-enmity** [comment]
Sounds good, we could perhaps support multiple instances of --tcp-port to open multiple ports, but I'm not sure if we have short-term use case for it, and from the long-term perspective the flag will probably go away at some time in favor of some config file.

**Comment by ncoghlan** [comment]
#21 has been merged, so this is working again.
