### ISSUE TITLE
"RTTVAR has grown" error from nmap

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/prototype#219]
A couple of times now we've seen CI fail due with multiple instances of a warning message from nmap (`RTTVAR has grown to over 2.3 seconds, decreasing to 2.0`) before finally reporting that mapping of source ports to target ports had failed.

Example from #205: https://ci.centos.org/job/leapp-integration-tests/399/console

A previous case where we saw the same behaviour, only for it to disappear on a retest: https://github.com/leapp-to/prototype/pull/201#issuecomment-310259421

**Comment by ncoghlan** [comment]
The first time I saw it, I assumed that the implementation of #202 would keep it from ever happening again, but the recurrence after rebasing #205 suggests that assumption was incorrect.

**Comment by ncoghlan** [comment]
Another example of the failure: https://ci.centos.org/job/leapp-integration-tests/400/console (this time when running via the Cockpit plugin)

**Comment by mfranczy** [comment]
I will try to resolve that by increasing ```--host-timeout```

**Comment by ncoghlan** [comment]
Closing on the assumption that #227 was the culprit here (as that would have prevented the system querying machinery from switching over to the `psutil` based scan added in #202).

If we see the problem again even with #227 applied, we'll reopen this.
