### ISSUE TITLE
Consolidate usage of sudo in integration tests

### ISSUE THREAD

**Issue by shaded-enmity** [leapp-to/prototype#22]
We shouldn't require sudo binary to be present on the system if we're already `uid = 0`.

**Comment by ncoghlan** [comment]
For other projects, we've dealt with this kind of thing by injecting additional helpers onto the `behave` context object, so that's probably a good option here as well.

**Comment by ncoghlan** [comment]
My current plan is to add three new classes to `enviroment.py`:

* `MachineHelper` (with the Vagrant commands as methods)
* `MigrationHelper` (with the Leapp commands as methods)
* `RequestHelper` (with the HTTP requests and comparisons as methods)

And then in the `before_scenario` hook, add an instance of each class to the context, which the test steps can then use.

**Comment by ncoghlan** [comment]
https://github.com/leapp-to/prototype/pull/24 moves all of the test helpers into the environment file and updates the documentation and test step definitions accordingly.
