### ISSUE TITLE
Always reprovision test VMs even without "ensure_fresh=yes"

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/prototype#28]
At the moment, test VMs only have their Ansible playbooks run when `ensure_fresh` is set to `yes` in the VM definition step.

This causes two problems:

- `ensure_fresh=no` can not only miss `Vagrantfile` changes, but also changes to the Ansible roles and playbooks
- `ensure_fresh=yes` is really slow, since it completely destroys and recreates the VM from scratch, but is currently the only way to specify that a test should re-run the Ansible playbook for a VM definition

My proposed resolution: update the tests to always pass the `--provision` flag to `vagrant up`.

That way any changes to the Ansible files will be picked up automatically on the next test run (when running the tests locally), and in CI it can be used to provide greater isolation between features by allowing the Ansible playbooks to be used to reset certain aspects of the VM to a known state

**Comment by shaded-enmity** [comment]
This will also help us to make sure that all our Ansible tasks are idempotent since during re-provision all non-idempotent tasks will error.

**Comment by ncoghlan** [comment]
PR: https://github.com/leapp-to/prototype/pull/40

**Comment by pcahyna** [comment]
Should start_vms.sh be changed in the same way?

**Comment by ncoghlan** [comment]
@pcahyna Indeed it should, and that also reminds me we were going to move those inside their respective directories (`demo` and `integration-tests`).

**Comment by ncoghlan** [comment]
PR to update the helper scripts: https://github.com/leapp-to/prototype/pull/44

I found while doing that that they'd bitrotted somewhat relative to the way the integration tests worked, so it's a general update, rather than just adding the `--provision` option.

**Comment by ncoghlan** [comment]
#44 is merged, so we're always reprovisioning the VMs by default now.
