### ISSUE TITLE
Decide on Python environment management strategy

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/prototype#30]
The current tests separate the LeApp tool execution environment from the testing environment just by explicitly invoking `leapp-tool.py` with the system Python 2 interpreter.

This only works as long as `leapp-tool.py` has no Python level dependencies - it fails once we start expecting to be able to import other modules (such as DBus Python bindings)

I see three possible paths forward here:

1. We update the integration tests to do a `pipsi install` of any runtime components written in Python that have separate dependencies, which will give them their own isolated virtual environment distinct from the one being used to run the tests. The main downside is having to write `setup.py` scripts for the affected pieces, but the related upsides are ensuring that the integration tests won't *need* to be in the same repository as the application components (even if we find it convenient to keep them there for now), as well as making it easier to potentially switch to RPM-based installation at a later date.

2. We make it a hard requirement that LeApp be single-source compatible across both Python 2 and 3 from the start, and opt for the Glib-based Python 2/3 compatible `pydbus` over the pure Python `txdbus` (which only has very partial Python 3 support at this point). 

3. We assume LeApp will use SCLs or Docker to run on RHEL/CentOS 7, and just make it a Python 3 only app, freeing us up to just run it in the same environment as the test runner, as well as allowing us to use the native async features in Python 3 (with the same pydbus vs txdbus trade-off - gaining Python 3 compatibility at the expense of gaining an additional system API dependency)

My own inclination is towards Option 3 for now - we don't know exactly what our eventual packaging is going to look like, and it will be a lot nicer to start with Python 3 and then make any allowances we need to make for Python 2.7 later rather than vice-versa.

The additional binary dependency needed to run `pydbus` isn't ideal, but has the other following benefits:

- it relies on `PyGI` (GOBject Introspection), and hence builds on the same interface the desktop use
- it's already packaged for Fedora, while `txdbus` isn't

**Comment by shaded-enmity** [comment]
While I don't personally like it myself, I think that going with Python 2.X will be the safest option, especially considering that once we start working beyond the lift & shift scenario, we may need to execute a lot of code in the guest system, which will most likely be EL6/7 or even EL5, and Python 2.X just seems like the safest choice.

**Comment by ncoghlan** [comment]
I'm actually OK with that, since the pay-off is that instead of relying on the glib bindings we get to use the nicer API offered by the pure Python `txdbus`. We'd then add Python 3 support in parallel with improvements to the Python 3 compatibility in `txdbus`.

To go down that path, I think what we'll need to do is:

1. Declare that the current Pipfile is specifically for the integration tests, *not* the software itself
2. Make a `src` directory, move `leapp-tool.py` into that, and add an appropriate `setup.py` file
3. Add `pipsi` as another test dependency
4. Add a `before_all` step in the integration tests that runs `pipsi install --python /usr/bin/python2 src/`
5. Change the test helper to run an unqualified `leapp-tool.py` so it finds the installed one, rather than the one in the source directory

**Comment by ncoghlan** [comment]
I'm marking this as resolved (since we've made the decision) and filed https://github.com/leapp-to/prototype/issues/33 for the actual implementation work.
