### ISSUE TITLE
Pick a license for the prototype

### ISSUE THREAD

**Issue by ncoghlan** [leapp-to/prototype#36]
For #33, I need a license to put into the package metadata.

I don't have any particularly strong preference, so my default choice would be to use "Apache License (2.0)" (and I'll use that in the draft PR), but GPLv2+ or GPLv3 would also be reasonable options.

**Comment by ncoghlan** [comment]
For the time being, I'm using LGPLv2+, based on the license used by the Cockpit project.

**Comment by vmindru** [comment]
just my 5 czech korunas - hence i am not really a good "legal" person I usually use https://choosealicense.com/  this might help and guide to choose and then take a proper decision depending on how permissive/defensive the license has to be.

**Comment by ncoghlan** [comment]
https://github.com/leapp-to/prototype/pull/102/ currently nominates GPLv2+ in the draft RPM metadata and has a placeholder entry for the `COPYING` file, so we should resolve this prior to merging that (otherwise we may end up with conflicting licensing guidance in different parts of the project).

My own inclination is to stick with the LGPLv2+ that I used in the Python level metadata, and add a suitable `COPYING` file as part of the RPM packaging PR.

**Comment by vinzenz** [comment]
LGPLv2+ it is, I just randomly picked something for the spec file - The general consensus seemed to have settled on LGPLv2+ which is fine with me.

@vmindru  @shaded-enmity agreed?

**Comment by ncoghlan** [comment]
The COPYING file has been added, and the packaging metadata aligns with that, so closing this.
